### ISSUE TITLE
connecting to private zulip

### ISSUE THREAD

**Issue by rawray7** [zulip/zulip-ios#14]
sorry to pester - but i'm trying to plan a potential zulip integration with my team operations. any word on timing for the released iOS app to support connection to private zulip servers? is this just waiting on Apple? couldn't quite tell from the description in https://github.com/zulip/zulip/blob/master/README.prod.md

**Comment by timabbott** [comment]
Oops, the iOS docs there are just out of date -- that was resolved months ago.  I'll fix that in README.prod.md.  Thanks for reporting this!

**Comment by timabbott** [comment]
(Pushed the README.prod.md update; thanks again for reporting this!)
