### ISSUE TITLE
Item not Available

### ISSUE THREAD

**Issue by edkirk30** [zulip/zulip-ios#26]
The iOS app doesn't appear to be available in the UK app store?

**Comment by timabbott** [comment]
It isn't available in any app store -- this is the old Dropbox app and is no longer developed.  However https://github.com/zulip/zulip-mobile will be soon.

**Comment by edkirk30** [comment]
Should I add an issue to the main repo then to get the public website and in-house zulip server updated with this info, instead of the old app store links? A bit confusing for a new time zulip user like myself

**Comment by timabbott** [comment]
Yes, great idea.  Dropbox removed it in just the last few weeks, and it is confusing...
