### ISSUE TITLE
Build Failed No such file or directory:  BrowserViewController.m

### ISSUE THREAD

**Issue by sunyazhou13** [zulip/zulip-ios#5]
clang: error: no such file or directory: '/Users/wwwbaiducom/Downloads/zulip-ios-master/ThirdParty/WebViewController/Browser Demo/BrowserViewController (Copy to your App)/BrowserViewController.m'

**Comment by lfranchi** [comment]
@sunyazhou13 did you run `git submodule init && git submodule --recursive update`? Give that a shot :)

**Comment by Hoodps** [comment]
git submodule update --init --recursive

**Comment by timabbott** [comment]
Closing since the fix for this is in the README.
