### ISSUE TITLE
Certificate Handling broken - Godaddy G2 cert

### ISSUE THREAD

**Issue by dupree972** [zulip/zulip-ios#6]
The zulip iOS client will not log into tulip server using fully signed cert. I have a zulip instance where the hostname zulip.company.com has a GoDaddy cert that matches the hostname, DNS name and reverse lookup name zulip.company.com. When I attempt to connect it never gets past the passing cert stage, I did a packet capture of my iPhone using the rvictl tool but github won't let me attach a pcap, everything looks fine then it just stops and get the "Uh oh, Something happened we didn't expect message" I am stumped what is stopping it from proceeding.

**Comment by lfaraone** [comment]
Are you serving the intermediate certificate chain, too?

**Comment by dupree972** [comment]
It looks like it goes and hit’s godaddy for it. I also tried installing the intermediate in profiles on the iPhone. Is there something I should do to munge those certs together. It does not give a cert error in a browser.
Bill

**Comment by dupree972** [comment]
I used the gd_bundle-g2-g1.crt from GoDaddy so that should have the whole chain I would think.
Bill

**Comment by lfaraone** [comment]
Can you verify the chain is being sent? See for example:

https://www.ssllabs.com/ssltest/analyze.html?d=zulip.com&s=54.244.50.68&latest

"Certification Paths" should go up to something in the trust store.

Checking in the browser isn't in-and-of-itself a great test, because browsers often cache intermediate certs.

**Comment by dupree972** [comment]
Got it to work, had to tinker with the cert and nginx to add all the intermediaries.  Interestingly just combining what is in the go-daddy repository as the intermediary with the cert is not sufficient.
Thanks,
Bill
